apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service-deployment
  labels:
    app: media-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: media-service
  template:
    metadata:
      labels:
        app: media-service
    spec:
      containers:
        - image: "761018889743.dkr.ecr.ap-southeast-2.amazonaws.com/media-microservice:latest"
          name: media-microservice
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: MODE
              valueFrom:
                secretKeyRef:
                  name: media-service-secret
                  key: MODE
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: media-service-secret
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: media-service-secret
                  key: AWS_SECRET_KEY
            - name: AWS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: media-service-secret
                  key: AWS_BUCKET_NAME
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: media-service-secret
                  key: AWS_REGION
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: media-service-secret
                  key: DB_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: media-service-secret
                  key: DB_PASSWORD
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: media-service-secret
                  key: DB_USER
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: media-service-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: media-service-secret
                  key: DB_PORT
          resources:
            requests:
              memory: "128Mi"
              cpu: "128m"
            limits:
              memory: "256Mi"
              cpu: "256m"
---
apiVersion: v1
kind: Service
metadata:
  name: media-cluster-ip-service
spec:
  selector:
    app: media-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
